# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.1.0
_src_path: https://github.com/napari/napari-plugin-template
display_name: Testgl
email: brisvag@gmail.com
full_name: Lorenzo Gaifas
github_repository_url: https://github.com/brisvag/testgl
github_username_or_organization: brisvag
include_reader_plugin: false
include_sample_data_plugin: false
include_widget_plugin: false
include_writer_plugin: false
install_dependabot: true
install_precommit: true
license: BSD-3
module_name: testgl
plugin_name: testgl
short_description: testgl
